modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="synceddoors"
version="1.0.0"
displayName="Synced Doors"
description='''
Двойные двери открываются и закрываются вместе (рукой и от редстоуна),
двойные калитки тоже. Для дверей, люков и калиток добавлены звук и частицы.
Работает с дверями из других модов, если они основаны на ванильных классах.
'''

[[dependencies.synceddoors]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.synceddoors]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
